module.exports = {
    rules: {
        'body-leading-blank': [1, 'always'],
        'body-max-line-length': [2, 'always', 80],
        'footer-leading-blank': [1, 'always'],
        'footer-max-line-length': [2, 'always', 80],
        'header-max-length': [2, 'always', 80],
        'subject-case': [
            2,
            'never',
            ['sentence-case', 'start-case', 'pascal-case', 'upper-case'],
        ],
        'subject-empty': [2, 'never'],
        'subject-full-stop': [2, 'never', '.'],
        'type-case': [2, 'always', 'lower-case'],
        'scope-case': [2, 'always', 'lower-case'],
        'type-empty': [2, 'never'],
        'scope-empty': [2, 'never'],
        'type-enum': [
            2,
            'always',
            [
                'build',
                'bump',
                'chore',
                'ci',
                'docs',
                'deploy',
                'feat',
                'fix',
                'perf',
                'refactor',
                'revert',
                'style',
                'test',
            ],
        ],
        'scope-enum': [
            2,
            'always',
            [
                'contracts',
                'circuits',
                'crypto',
                'dapp',
                'integration',
                'monorepo',
                'root',
                'subgraph',
            ],
        ],
    },
};
